---
# This playbook sends GET request to MongoDB and determine how many data points are missing
- name: Get count for missing points from MongoDB
  hosts: localhost
  gather_facts: false
  # vars_files:
  #   - vault_file.yml

  tasks:
    - name: Install pymongo
      pip:
        name: pymongo
        state: present

    # - name: Perform calculations
    #   python_script:
    #     script: |
    #       from pymongo import MongoClient
    #       client = MongoClient("mongodb+srv://wleong:{{ mongodb_password }}@cluster0.kt74jjh.mongodb.net/")
    #       database = client["StockTracker"]
    #       collection = database["Companies"]
    #       projection = {"_id": 0, "name": 1, "price": 1}
    #       cursor = collection.find({"name": "MSFT"}, projection)
    #       for doc in cursor:
    #           latest_date = doc["price"][0]["date"]
    #       return latest_date
    # - name: Confirm date
    #   ansible.builtin.debug:
    #     var: latest_date
    - name: Get all points in database
      ansible.builtin.script:
        cmd: find_missing_points.py get_curr_points
        executable: ../../venv/bin/python3
      register: filtered_points

    - name: Confirm filtered points
      ansible.builtin.debug:
        var: filtered_points.stdout
