---
# The playbook sends GET request to AlphaVantage to obtain full historical prices for a particular company
- name: Get data and save to variable
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault_file.yml

  tasks:
    - name: Make API request
      ansible.builtin.uri:
        url: "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=AAPL&outputsize=full&apikey={{ alphavantage_api_key }}"
        method: GET
        status_code: 200
        body_format: json
        return_content: true
        timeout: 60
      register: api_response

    - name: Debug API response
      ansible.builtin.debug:
        var: api_response.json

    - name: Extract time series
      ansible.builtin.set_fact:
        time_series_list: >-
          [{ "date": "{{ item.key }}", "close": "{{ item.value['4. close'] }}" }]
      with_dict: "{{ api_response.json['Time Series (Daily)'] }}"
      register: extracted_data

    - name: Convert extracted data
      ansible.builtin.set_fact:
        final_output: "{{ extracted_data.results | map(attribute='ansible_facts.time_series_list') | list | flatten }}"

    # - name: Print final output
    #   ansible.builtin.debug:
    #     var: final_output

    - name: Print completion
      ansible.builtin.debug:
        msg: "Data extracted for something"
