---

- name: Send to kafka
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Validating if zookeeper is up and listening on port 2181
      wait_for:
        host: localhost
        port: 2181
        delay: 10
        timeout: 30
        state: started
        msg: "Zookeeper is not running"

    - name: Validating if kafka is up and listening on port 9092
      wait_for:
        host: localhost
        port: 9092
        delay: 10
        timeout: 30
        state: started
        msg: "Kafka is not running on 9092"

    - name: Send contents to kafka
      ansible.builtin.script:
        cmd: producer.py filtered_data.json
        executable: ../../venv/bin/python3
